Description:  RDS Resources for Udacity - Design for Availability, Resilience, and Reliability

Parameters:
  Subnet1:
    Description: Database VPC subnet 1 (using multiple subnets for multi-az configuration)
    Type: String

  Subnet2:
    Description: Database VPC subnet 2 (using multiple subnets for multi-az configuration)
    Type: String
  
  DBInstanceClass:
    Description: RDS instance type
    Type: String
    Default: db.t3.micro

  DatabaseSecurityGroup:
    Description: Security group for the RDS instance
    Type: String
  
  DBUsername:
    Description: DB username
    Type: String

  DBPassword:
    Description: DB username
    Type: String
  
  SourceDBId:
    Description: Source DB ID if a read replica is being created
    Type: String
    Default: ''

  SourceDBRegion:
    Description: Source DB region if a read replica is being created
    Type: String
    Default: ''

Conditions:
  IsReadReplica: !And [ !Not [ !Equals [ !Ref SourceDBId, '' ] ], !Not [ !Equals [ !Ref SourceDBRegion, '' ] ] ]
  
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: primary
      DBName: udacity
      DBSubnetGroupName: !Ref RDSSubnetGroup
      AllocatedStorage: 20
      StorageType: gp2
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: true
      PubliclyAccessible: false
      SourceDBInstanceIdentifier: !If [ IsReadReplica, !Ref SourceDBId, !Ref 'AWS::NoValue' ]
      SourceRegion: !If [ IsReadReplica, !Ref SourceDBRegion, !Ref 'AWS::NoValue' ]
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
    
  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: RDS Subnet Group
      SubnetIds: 
        - !Ref Subnet1
        - !Ref Subnet2

Outputs:
  DatabaseId:
    Description: Database ID
    Value: !Ref RDSInstance